{ settings, ... }:
{
  imports = [
    ./programs.nix
    ./development.nix
    ./comfyui.nix
    ./discord.nix
    ./niri.nix
    ./niri-rules.nix
    ./inir.nix
    ./qt-theme.nix
    ./kitty.nix
    ./session-services.nix
    ./application-themes.nix
    ./audio.nix
    ./music.nix
    ./bedrock-on-linux.nix
    ./no-network-tray.nix
    ./clash-verge.nix
  ];

  home.username = settings.username;
  home.homeDirectory = "/home/${settings.username}";
  home.stateVersion = settings.stateVersion;

  programs.home-manager.enable = true;

  xdg = {
    enable = true;
    autostart.enable = true;
    # These files are generated by Home Manager's GTK module.  Do not attempt
    # to create another fixed-name .hm-backup when replacing an older
    # generation, since that backup may already exist.
    configFile."gtk-3.0/settings.ini".force = true;
    configFile."gtk-4.0/settings.ini".force = true;
  };

  home.sessionVariables = {
    BROWSER = "zen";
    TERMINAL = "kitty";
    NIXOS_OZONE_WL = "1";
    MOZ_ENABLE_WAYLAND = "1";
  };
}
